### PR TITLE
Update Homepage

### PR DESCRIPTION
**Pull request by chartgerink**
This PR adds an updated Homepage, with new elements to interest people in the resource.

Not all links work just yet, because the relevant pages do not exist yet. :-) Will ensure this gets tracked in an issue.

Inviting y'all for reviews to get some feedback if you're available. No pressure to prioritize this if you're swamped!

### CODE REVIEW

**Comment by Elisa-on-GitHub** [comment]
@chartgerink I'm not sure what it means that my review was requested. Should I merge the PR when I like what the new homepage looks like? But I see that you also requested a review from the others. Should I wait for their approval?

**Comment by chartgerink** [comment]
Hi @Elisa-on-GitHub 👋 Feedback on the revised homepage will help refine it. You don't need to merge this - all I am looking for is thoughts on how I translated your input into a homepage.

You can view it through this link: https://deploy-preview-35--ubvu-open-handbook.netlify.app/

**Review by Elisa-on-GitHub — COMMENTED** [review]
I can comment insofar that I can say that I'm impressed with the new look of the homepage and that I think it looks beautiful and shows the things that we said were important about this project.
I can't really comment on all the huge code blocks, especially those that mention facebook (?), for example _extensions/clearmatics/qreacto/react-dom.min.js, because I don't know what this code does or where it goes.

One thing that I think would be good when I see this is if the little tiles that sum up the benefits of using the resource could be interactive/clickable. For example, the 'collaborative' tile could refer people to the contributing page, and Quality control could go to a page where we explain that process.
I'm not sure if this is indeed the plan but doesn't work yet because it's only a preview; or if this isn't possible. It's just that I, as a user, would expect this to be clickable (also because the VU website has clickable tiles that look kind of similar).

Another thing that I noticed is that there is a lot of whitespace above the 'This is a new project' banner and between the 'Learn how to contribute' and the 'Benefits'. For people with a smaller screen, it may not be obvious that they can scroll down (screenshots below of how this looks on my large schreen and how it looks on my smaller screen).

How this looks on my larger screen
afbeelding

How this looks on my smaller screen:
afbeelding

But overall I think it's beautiful! Thank you, enormously!

**Review by jhrudey — COMMENTED** [review]
I  only had time for a quick look, but I really like the layout as a starting page. It's nice and clean and gives a good brief summary of what the page will over, but also allows the user to quickly get to the collab page if that's what they are there for. Thank!

**Comment by chartgerink** [comment]
Thanks both for your feedback! I opened a few issues to keep track of the things mentioned here. 

I will merge as communications needs something more to allow us to move forward with the domain..

**Pull request merged**
