### PR TITLE
Add trainings topic

### PR DESCRIPTION
**Pull request by chartgerink**
This PR adds the "Trainings" topic that provides a list of trainings. This list was provided by Tycho Hofstra and Stephanie van de Sandt.

I adjusted "Keywords" to "Topics" as keywords do not exist in the handbook as such. Topics is more informative to tell readers what related topics are discussed. We can add hyperlinks to the relevant topics or identify additional topics to write about.

### CODE REVIEW

**Comment by chartgerink** [comment]
@TMHofstra in #145 asked: "Would it be possible to add extra space between the topics in trainings.qmd?"

We can add an extra line to demarcate the sections, if you'd like. It would look something like this:

---

What would be enough extra space, I am not sure, and in general, customizing documents like this is not scalable 👍

**Comment by chartgerink** [comment]
@TMHofstra – are you able to provide any further updates on this topic, for example during our third hackathon? 

The current information is not sufficient to be merged and needs to be added to and vetted before we can start the review process. 👍

**Comment by TMHofstra** [comment]
I've gone over the page again and I think it is publishable as it is right now.

**Comment by chartgerink** [comment]
Okay, thanks @TMHofstra for going over it. I am glad that you are happy with the results 😊

I will be removing the empty license fields as these are not informative. I will also comment out the entirety of "Writing a Data Management Plan" as there is no actionable information (for example, URL) in there at this time. If that changes, we are open to PR incorporating that info.

**Review by Jolien-S — APPROVED** [review]
I'm glad that this information will become part the handbook soon!

I think this is a good start and this is definitely publishable. 

However, I think we should try to keep adding more information to make the page even more useful. For example, when looking at it, I feel like we should also provide links to registration forms/actual scheduled courses where relevant. I think when people see this list, they want to be able to go to a place where they can actually sign up for these events. For the Carpentries it's nice to have a URL to the lessons, but I think for researchers it would be more useful to (also) get a link to the upcoming scheduled courses.

Regarding Writing a DMP: Would adding a link to the registration forms of upcoming courses be actionable enough? I would very much like this course to be listed here, because at the moment we don't have a very visible/easily findable place for this course, whereas it is being taught very often. Hence, it would be useful if this course gets a reference in the handbook soon.

**Comment by chartgerink** [comment]
@Jolien-S yes that would be great! I have little purview on relevant links, and I agree being able to sign up is an expected action.

If you have relevant links to any of the trainings, especially "Writing a DMP", send it my way and I am happy to add it! In the meantime I will merge this change and refer to #193 for continuing this work item 👍

**Pull request merged**
